version: 2
jobs:
  build-node8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: ./scripts/circleci/run.sh
  build-node9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: ./scripts/circleci/run.sh
  build-node10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: ./scripts/circleci/run.sh
  build-node11:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: ./scripts/circleci/run.sh
  build-node12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: ./scripts/circleci/run.sh
workflows:
  version: 2
  build_nodejs:
    jobs:
      - build-node8
      - build-node9
      - build-node10
      - build-node11
      - build-node12
